Tarea 2
profedotc/jose_castanio pull request #2
Opened 2019-06-12 18:54 UTC by Castam

2019-06-17 21:23 UTC, profedotc requested changes

2019-06-17 21:23 UTC, profedotc commented on main.c
> +		gol_step(world, i%2);
Si vas a usar el operador módulo debes declarar tu entero como `unsigned int`. Si un entero llega a su valor positivo máximo se dice que **desborda**, pasa a valer el menor número negativo representable. El módulo no trabaja con los números negativos como tu podrías esperar.

2019-06-17 21:23 UTC, profedotc commented on makefile
> +main.o: main.c
`main.o` también depende de `gol.h`

2019-06-17 21:23 UTC, profedotc commented on gol.c
> +void gol_print(struct gol *gol)
Esta función debe recibir un puntero a constante, puesto que no modifica el mundo: `const struct gol *gol`

2019-06-17 21:23 UTC, profedotc commented on gol.c
> +static int count_neighbors(struct gol *gol, int x, int y);
No has cambiado el nombre de estas funciones en todos sitios. Tu programa no compila.

2019-06-19 15:29 UTC, Castam commented
Ya he hecho las correcciones Carlos, pero no me deja hacer otro pull para
que las veas. ¿Sigo trabajando en la tarea 4?

El lun., 17 jun. 2019 a las 23:23, Profe C (<notifications@github.com>)
escribió:

> *@profedotc* requested changes on this pull request.
> ------------------------------
>
> In main.c
> <https://github.com/profedotc/jose_castanio/pull/2#discussion_r294514700>:
>
> >  		// TODO: Itera
>
> -		gol_step(world, world_copy);
>
> +		gol_step(world, i%2);
>
>
> Si vas a usar el operador módulo debes declarar tu entero como unsigned
> int. Si un entero llega a su valor positivo máximo se dice que *desborda*,
> pasa a valer el menor número negativo representable. El módulo no trabaja
> con los números negativos como tu podrías esperar.
> ------------------------------
>
> In makefile
> <https://github.com/profedotc/jose_castanio/pull/2#discussion_r294516738>:
>
> > @@ -0,0 +1,16 @@
>
> +.PHONY: all clean
>
> +
>
> +all: gol
>
> +
>
> +gol: main.o gol.o
>
> +	gcc main.o gol.o -o mi_prog
>
> +	
>
> +main.o: main.c
>
>
> main.o también depende de gol.h
> ------------------------------
>
> In gol.c
> <https://github.com/profedotc/jose_castanio/pull/2#discussion_r294522452>:
>
> >  		}
>
>  	};
>
>  }
>
>
>
> -void gol_print(bool world[ROWS][COLUMNS][2], int z)
>
> +void gol_print(struct gol *gol)
>
>
> Esta función debe recibir un puntero a constante, puesto que no modifica
> el mundo: const struct gol *gol
> ------------------------------
>
> In gol.c
> <https://github.com/profedotc/jose_castanio/pull/2#discussion_r294523968>:
>
> > @@ -2,6 +2,10 @@
>
>
>
>  #include <stdio.h>
>
>
>
> +static bool get_cell(struct gol *gol, int x, int y);
>
> +
>
> +static int count_neighbors(struct gol *gol, int x, int y);
>
>
> No has cambiado el nombre de estas funciones en todos sitios. Tu programa
> no compila.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/profedotc/jose_castanio/pull/2?email_source=notifications&email_token=AK2CTYKV5UECAEG35ZUS6W3P276GHA5CNFSM4HXO4W2KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB3ZARZY#pullrequestreview-250743015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK2CTYK5EIQWXSLPPRTVPG3P276GHANCNFSM4HXO4W2A>
> .
>

2019-06-25 19:46 UTC, merged