Tarea 4
profedotc/jose_castanio pull request #3
Opened 2019-06-29 15:29 UTC by Castam

2019-07-01 22:33 UTC, profedotc commented on mem_test.c
> +#define COLUMNS 15
Mejor si pruebas con un mundo rectangular en lugar de cuadrado

2019-07-01 22:51 UTC, profedotc requested changes

2019-07-01 22:51 UTC, profedotc commented on gol.h
> +	bool **worlds[2];
Aquí tienes que añadir un par de campos para guardar el tamaño de tu mundo. Así no tienes que pasárselo a todos los métodos.

Además ya no tienen sentido aquí las macros `ROWS` y `COLUMNS`, puesto que el mundo de tu librería ya no tiene un tamaño fijo. Debes moverlas al `main.c`, donde se las pasarás a `gol_alloc()`

2019-07-01 22:51 UTC, profedotc commented on gol.h
> -void gol_step(struct gol *gol);
Lo dicho, ninguno de estos métodos debe cambiar su interfaz

2019-07-01 22:51 UTC, profedotc commented on makefile
> +test: mem_test valgrind
`test` depende sólo de `valgrind` y `valgrind` ya depende de `mem_test`. No tiene sentido que `test` dependa de los dos

2019-07-01 22:51 UTC, profedotc commented on makefile
> +mem_test.o: gol.c gol.h
`mem_test.o` no depende de `gol.c`, depende de `mem_test.c`

2019-07-01 22:51 UTC, profedotc commented
* Has vuelto a subir el binario, más otro archivo `.Rhistory`. Actualiza tu `.gitignore`
* Prueba con un tamaño rectangular, tienes un problemas con la memoria

2019-07-02 20:26 UTC, profedotc requested changes
Te faltan todavía por corregir varias cosas de las que te comenté

2019-07-02 20:26 UTC, profedotc commented on gol.c
> +		return gol -> worlds[s][x * gol -> n_columns + y];
esto no tiene sentido ¿por qué compruebas dos veces los límites?

2019-07-04 09:17 UTC, Castam commented
Perfecto Carlos, esta tarde estará todo corregido.
Lo subiré a un commit a la espera de que pueda hacer otro pull request, que
he visto que aun no puedo.
Para el fichero gol.c con la doble comprobación del if me habré equivocado
de fichero, ya que eso lo utilicé para no equivocarme y lo puse dos veces y
lo fui retocando con los cambios de la tarea, pero lo borré, no se por qué
te aparece.
Un saludo y esta tarde te realizo el commit con las correcciones realizadas
y la tarea 5 finalizada.
Muchas gracias de nuevo.

El mar., 2 jul. 2019 a las 22:26, Profe C (<notifications@github.com>)
escribió:

> *@profedotc* requested changes on this pull request.
>
> Te faltan todavía por corregir varias cosas de las que te comenté
> ------------------------------
>
> In gol.c
> <https://github.com/profedotc/jose_castanio/pull/3#discussion_r299669335>:
>
> >  {
>
>  	/*
>
>  	 * TODO: Devuelve el estado de la célula de posición indicada
>
>  	 * (¡cuidado con los límites del array!)
>
>  	 */
>
> -	if ((x >= 0) && (x < rows) && (y >= 0) && (y < columns)) {
>
> -		return gol -> worlds[CURRENT][x][y];
>
> +	if ((x >= 0) && (x < gol -> n_rows) && (y >= 0) && (y < gol -> n_columns)) {
>
> +		fix_coords(gol, &x, &y);
>
> +		return gol -> worlds[s][x * gol -> n_columns + y];
>
>
> esto no tiene sentido ¿por qué compruebas dos veces los límites?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/profedotc/jose_castanio/pull/3?email_source=notifications&email_token=AK2CTYPNU57376TYUON4VVLP5O2WXA5CNFSM4H4KT5Z2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5JX4OA#pullrequestreview-257130040>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK2CTYO5Z6ATMPFU4WCXSD3P5O2WXANCNFSM4H4KT5ZQ>
> .
>

2019-07-04 21:09 UTC, profedotc commented
* Todavía tienes que corregir `get_cell()`
* Tu `make test` no compila, actualiza `mem_test.c`
* Has vuelto a subir un binario al repositorio

El proceso que debes de seguir antes de hacer commit es el siguiente:
1. `git status`: Verifico que he cambiado los archivos que quería cambiar y que no hay nada sin ignorar que no quiera subir al repositorio
2. `git add <file1> <file2> ...`: Añado los cambios que deseo incluir en el commit
3. `git status`: Verifico que he añadido lo que quería añadir y nada más (no hay añadido ningún binario)
4. `git commit`: Mensaje de commit descriptivo
5. `git push`

Ve actualizando tu `.gitignore` para ayudarte a no subir al repositorio nada que no debas.

2019-07-06 10:43 UTC, Castam commented
Buenas tardes Carlos, he modificado mem_test para que funcione
correctamente y realice el valgrind correctamente, en get_cell ya eliminé
la doble comprobación y creo que ahora actúa como debería, o al menos no me
da errores y por último no comprendo a qué te refieres con lo del binario
en el repositorio, ya actualicé el gitignore para que no apareciera el
.Rhistory pero no se a qué te refieres.
Muchas gracias de nuevo y disculpa las molestias

El jue., 4 jul. 2019 a las 23:09, Profe C (<notifications@github.com>)
escribió:

>
>    - Todavía tienes que corregir get_cell()
>    - Tu make test no compila, actualiza mem_test.c
>    - Has vuelto a subir un binario al repositorio
>
> El proceso que debes de seguir antes de hacer commit es el siguiente:
>
>    1. git status: Verifico que he cambiado los archivos que quería
>    cambiar y que no hay nada sin ignorar que no quiera subir al repositorio
>    2. git add <file1> <file2> ...: Añado los cambios que deseo incluir en
>    el commit
>    3. git status: Verifico que he añadido lo que quería añadir y nada más
>    (no hay añadido ningún binario)
>    4. git commit: Mensaje de commit descriptivo
>    5. git push
>
> Ve actualizando tu .gitignore para ayudarte a no subir al repositorio
> nada que no debas.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/profedotc/jose_castanio/pull/3?email_source=notifications&email_token=AK2CTYJGTQTTJISAXJIQVZDP5ZRIFA5CNFSM4H4KT5Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZIELYA#issuecomment-508577248>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK2CTYOQ5OQJXFAHBTTILB3P5ZRIFANCNFSM4H4KT5ZQ>
> .
>

2019-07-07 10:30 UTC, profedotc commented
* Tienes subido a tu repositorio el ejecutable `gol`: `git rm gol` + añadirlo a `.gitignore`
* No has resuelto la doble comparación de `get_cell()`. Compruebas los límites del array en `get_cell()` y luego llamas a `fix_coords()`, que vuelve a comprobar los límites del array. La forma correcta de hacerlo sería así:

```c
static bool get_cell(const struct gol *gol, enum state s, int x, int y)
{
	fix_coords(gol, &x, &y);
	return gol -> worlds[s][x * gol -> n_columns + y];
}
```

2019-07-07 10:40 UTC, Castam commented
Ok, todo correcto y cambios hechos de nuevo. Gracias

El dom., 7 jul. 2019 12:30, Profe C <notifications@github.com> escribió:

>
>    - Tienes subido a tu repositorio el ejecutable gol: git rm gol +
>    añadirlo a .gitignore
>    - No has resuelto la doble comparación de get_cell(). Compruebas los
>    límites del array en get_cell() y luego llamas a fix_coords(), que
>    vuelve a comprobar los límites del array. La forma correcta de hacerlo
>    sería así:
>
> static bool get_cell(const struct gol *gol, enum state s, int x, int y)
>
> {
>
> 	fix_coords(gol, &x, &y);
>
> 	return gol -> worlds[s][x * gol -> n_columns + y];
>
> }
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/profedotc/jose_castanio/pull/3?email_source=notifications&email_token=AK2CTYPEF7ANKXKX5JKQAILP6HAVVA5CNFSM4H4KT5Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZLIZWA#issuecomment-508988632>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK2CTYKAONAGOWKEYNZTHO3P6HAVVANCNFSM4H4KT5ZQ>
> .
>

2019-07-07 12:35 UTC, merged

2019-07-07 13:53 UTC, Castam commented
Gracias de nuevo por todo.
Una última cosa, he visto que sale como la tarea 4, pero ahí está ya hasta
la 5, ¿Faltaría algo de la 5?

El dom., 7 jul. 2019 14:35, Profe C <notifications@github.com> escribió:

> Merged #3 <https://github.com/profedotc/jose_castanio/pull/3> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/profedotc/jose_castanio/pull/3?email_source=notifications&email_token=AK2CTYMZQ7QA6UOWW34MVLDP6HPKJA5CNFSM4H4KT5Z2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSLRTZ2Y#event-2464365803>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK2CTYOANUXUHZ5OFR5N7ALP6HPKJANCNFSM4H4KT5ZQ>
> .
>

2019-07-07 15:05 UTC, profedotc commented
corregido